# DRAKES DNA Model Evaluation Configuration

# Base paths
base_path: "/n/holylabs/LABS/sitanc_lab/Users/mfli/DRAKES_test/data_and_model"

# Random seed
seed: 0

# CUDA device
cuda_device: 0

# Sampling parameters
num_sample_batches: 10
num_samples_per_batch: 64

# Likelihood calculation parameters
likelihood_steps: 128

# Model checkpoints to evaluate
models:
  finetuned_model: "mdlm/reward_bp_results_final/finetuned.ckpt"
  pretrained_model: "mdlm/outputs_gosai/pretrained.ckpt"
  zero_alpha_model: "mdlm/reward_bp_results_final/zero_alpha.ckpt"
  cfg_model: "mdlm/outputs_gosai/cfg.ckpt"

# CFG parameters
cfg_weight: 10
cfg_prob: 0.1

# Controlled sampling options (for pretrained model)
use_regular_sampling: true
use_tds_sampling: false
use_cg_sampling: false
use_smc_sampling: false

# TDS sampling parameters
tds_alpha: 0.5
tds_guidance_scale: 1000

# CG sampling parameters
cg_guidance_scale: 300000

# SMC sampling parameters
smc_alpha: 0.5

# Additional evaluation options
save_plots: true
save_sequences: true 