# Example configuration for comprehensive model evaluation
# This config will run all sampling methods on the pretrained model

# Base path to your models
base_path: '/n/holylabs/LABS/sitanc_lab/Users/mfli/DRAKES_test/data_and_model'

# Model paths (relative to base_path)
models:
  finetuned_model: 'mdlm/reward_bp_results_final/finetuned.ckpt'
  pretrained_model: 'mdlm/outputs_gosai/pretrained.ckpt'
  zero_alpha_model: 'mdlm/reward_bp_results_final/zero_alpha.ckpt'
  cfg_model: 'mdlm/outputs_gosai/cfg.ckpt'

# Sampling parameters
num_sample_batches: 10
num_samples_per_batch: 64

# CFG parameters
cfg_weight: 10
cfg_prob: 0.1

# TDS parameters  
tds_alpha: 0.5
tds_guidance_scale: 1000

# CG parameters
cg_guidance_scale: 300000

# SMC parameters
smc_alpha: 0.5

# Likelihood calculation parameters
likelihood_steps: 128

# Random seed
seed: 0

# CUDA device
cuda_device: '0' 